### PR TITLE
Customize configuration of Consul client

### PR DESCRIPTION
**Pull request by odiszapc**
I need to set timeout values, so I added 3 methods to do that. For further customization a method accepts custom http client builder added.

### CODE REVIEW

**Comment by odiszapc** [comment]
Another one from me, dude.

**Comment by rickfast** [comment]
OkHTTP is shaded into the JAR and I'd like to keep shaded libraries internal to the client. I'm fine with this functionality, but it needs to be abstracted away from OkHTTP.

**Comment by odiszapc** [comment]
Agree, I can expose only timeouts and hide builder for the OkHttp

**Comment by odiszapc** [comment]
OkHttp client is now encapsulated

**Comment by odiszapc** [comment]
Short question: why OkHTTP, why not Apache Http Client? Are there real benefits? Never worked with OkHTTP before

**Comment by rickfast** [comment]
I'm using OkHTTP because Retrofit uses it. Retrofit annotations make it easy to build http clients

**Pull request merged**
