### PR TITLE
Add datacenter to catalog and health endpoints

### PR DESCRIPTION
**Pull request by jplock**
https://www.consul.io/api/catalog.html#list-nodes-for-service
https://www.consul.io/api/health.html#list-nodes-for-service

### CODE REVIEW

**Comment by rickfast** [comment]
On vacation without laptop til Tuesday, so I won't be able to release this until then :/

**Comment by jplock** [comment]
No rush, thanks!

**Comment by jplock** [comment]
@rickfast think you'll be able to create a release later this week or next week with these fixes?

**Comment by rickfast** [comment]
Yup I'll do it now stand by

**Comment by rickfast** [comment]
`0.15.1`

**Pull request merged**
