### PR TITLE
Added SessionClient and Leader Election-related methods

### PR DESCRIPTION
**Pull request by vascokk**
Hi all,
In this pull request I added functionality for Leader Election as described here: [https://www.consul.io/docs/guides/leader-election.html](https://www.consul.io/docs/guides/leader-election.html)
Best regards,
Vasco

### CODE REVIEW

**Comment by rickfast** [comment]
rad. everything looks good. i'm re-running the build to rule out flakiness. if it fails again, we'll need to fix the broken tests before merging. thanks!

**Comment by rickfast** [comment]
<https://app.shippable.com/builds/5526a8ea5cb2750c00d8a974>

**Comment by rickfast** [comment]
Thanks!  I've included your changes in ```com.orbitz.consul:consul-client:0.8.3```

**Comment by vascokk** [comment]
Thanks, Rick! :)

**Pull request merged**
