### PR TITLE
Set default watch duration for caches in configuration

### PR DESCRIPTION
**Pull request by yfouquet**
The default value of 10 seconds is set 4 times in caches.
Set its value (once) in the default configuration file.

### CODE REVIEW

**Comment by alesharik** [comment]
Cast to `int` looks weird. Maybe it would be better to convert `watchSeconds` into `long`?

**Comment by yfouquet** [comment]
Hi @alesharik,
Thanks for the review.
It's not a good thing, you're right. However, I cannot convert watchSeconds to long would break the API for current users, so it is not possible.
Other solutions would be:
 - directly add getWatchDurationSeconds() in CacheConfig, but i don't really like it.
 - use Ints.saturatedCast (guava) which gets the nearest interger, but again i don't like it as it would hide issue with the value
 - use Math.toIntExact() (java.lang) which throws ArithmeticException is something go wrong with the cast.

I pushed a change with the last solution, what do you think?

**Comment by alesharik** [comment]
`toIntExact` with time looks a bit weird. How about creating something like this?
```java
static int getSeconds(Duration duration) {
    long seconds = duration.getSeconds();
    int castedSeconds = (int) seconds;
    if(castedSeconds != seconds) //This is from Math#toIntExact
        throw new IllegalArgumentException("The number of seconds in the duration must be <= " + Integer.MAX_VALUE);
    return castedSeconds;
}
```
This method hides all weird casts and throw more informative exception in case of error.

**Comment by yfouquet** [comment]
So here, you re-implement Ints#checkedCast from Guava which does the same thing than Math#toIntExact with a different exception. Would Ints#checkedCast would be better (semantically) ?

**Comment by alesharik** [comment]
It will look like `toIntExact` because of the thrown exception with misleading message like `integer overflow`. I believe that nobody expects ArithmeticException/IllegalArgumentException with `integer overflow` from some package-private class.

**Comment by yfouquet** [comment]
What about now:
 - cast is done using Ints#checkedCast (i have to cast somewhere)
 - protection from IllegalArgumentException is made in CacheConfig#getWatchDuration as the maximum duration of 10 minutes is checked (and so 600 always fits in an integer).
 - in case the value is too big (or negative), an exception is thrown with the appropriate message.

Is is good for you?

**Comment by alesharik** [comment]
Yes, thanks

**Pull request merged**
