### PR TITLE
Introduced acl and auth support

### PR DESCRIPTION
**Pull request by YannRobert**
basic support for the Consul ACL (providing token) + support for Basic Authentication (providing username+password)

Added support for the Consul ACL : a token can be provided to the Consul.Builder, this token will be added to every request as a query parameter.

Added support for Basic Authentication : in case you setup a reverse proxy in front of the Consul service (for additional security to the ACL, or as an alternative to the Consul ACL)

In both case, an Interceptor is added to the Retrofit client.

### CODE REVIEW

**Comment by rickfast** [comment]
Awesome thanks!

**Comment by YannRobert** [comment]
Thank you for merging so fast.
Would be possible to release ?

**Comment by rickfast** [comment]
Sure. Once I'm in the office

**Comment by rickfast** [comment]
0.11.2 is available

**Pull request merged**
