### PR TITLE
Fix maintenance route

### PR DESCRIPTION
**Pull request by jplock**
Related to https://github.com/OrbitzWorldwide/consul-client/commit/f459947cbbb645699deed63152c6c82a3ab07f12#commitcomment-20226372

### CODE REVIEW

**Comment by rickfast** [comment]
Thanks. About to get on a plane, but I will release a minor for you when I land

**Comment by jplock** [comment]
Thanks!

**Comment by rickfast** [comment]
`0.13.7` is now available with your fix.

**Comment by jplock** [comment]
@rickfast thanks!  I'm not seeing `0.13.7` on central yet - http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.orbitz.consul%22%20AND%20a%3A%22consul-client%22

**Comment by rickfast** [comment]
just redeployed. not sure what happened there

**Pull request merged**
